"""empty message

Revision ID: 02f4202766df
Revises: None
Create Date: 2016-10-10 01:04:11.763603

"""

# revision identifiers, used by Alembic.
revision = '02f4202766df'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('tutorial_tbl')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorial_tbl',
    sa.Column('tutorial_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('totorail_title', mysql.VARCHAR(length=100), nullable=False),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
