"""empty message

Revision ID: 350d71b917aa
Revises: da5a8b566ade
Create Date: 2016-10-14 23:27:14.171707

"""

# revision identifiers, used by Alembic.
revision = '350d71b917aa'
down_revision = 'da5a8b566ade'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sign_In', sa.Column('pincode', sa.Integer(), nullable=True))
    op.add_column('Sign_In', sa.Column('timestamp', sa.Float(), nullable=True))
    op.alter_column('Sign_In', 'complete_registration',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Sign_In', 'complete_registration',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_column('Sign_In', 'timestamp')
    op.drop_column('Sign_In', 'pincode')
    ### end Alembic commands ###
