"""empty message

Revision ID: 50589f022c12
Revises: be9fcda36ada
Create Date: 2016-10-14 18:08:02.710996

"""

# revision identifiers, used by Alembic.
revision = '50589f022c12'
down_revision = 'be9fcda36ada'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sign_In', sa.Column('gender', sa.String(length=6), nullable=False))
    op.alter_column('Sign_In', 'complete_registration',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Sign_In', 'complete_registration',
               existing_type=sa.Boolean(),
               server_default=sa.text("'0'"),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_column('Sign_In', 'gender')
    ### end Alembic commands ###
