"""empty message

Revision ID: 5f708a0dfb02
Revises: 350d71b917aa
Create Date: 2016-10-15 15:25:01.765173

"""

# revision identifiers, used by Alembic.
revision = '5f708a0dfb02'
down_revision = '350d71b917aa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email_id', sa.String(length=64), nullable=False),
    sa.Column('mob_no', sa.String(length=10), nullable=False),
    sa.Column('query', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id'),
    sa.UniqueConstraint('mob_no')
    )
    op.alter_column('Sign_In', 'complete_registration',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Sign_In', 'complete_registration',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_table('Queries')
    ### end Alembic commands ###
