"""empty message

Revision ID: 6dbfa40bbf09
Revises: 5f708a0dfb02
Create Date: 2016-10-16 19:01:22.638713

"""

# revision identifiers, used by Alembic.
revision = '6dbfa40bbf09'
down_revision = '5f708a0dfb02'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Queries', 'query',
               existing_type=mysql.VARCHAR(length=160),
               nullable=False)
    op.drop_index('email_id', table_name='Queries')
    op.drop_index('mob_no', table_name='Queries')
    op.alter_column('Sign_In', 'complete_registration',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Sign_In', 'complete_registration',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.create_index('mob_no', 'Queries', ['mob_no'], unique=True)
    op.create_index('email_id', 'Queries', ['email_id'], unique=True)
    op.alter_column('Queries', 'query',
               existing_type=mysql.VARCHAR(length=160),
               nullable=True)
    ### end Alembic commands ###
