"""empty message

Revision ID: 7adc828b6c7c
Revises: b647ea596827
Create Date: 2016-10-17 21:19:28.633620

"""

# revision identifiers, used by Alembic.
revision = '7adc828b6c7c'
down_revision = 'b647ea596827'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Queries', sa.Column('ques', sa.String(length=160), nullable=False))
    op.drop_column('Queries', 'query')
    op.alter_column('Sign_In', 'complete_registration',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Sign_In', 'complete_registration',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.add_column('Queries', sa.Column('query', mysql.VARCHAR(length=160), nullable=False))
    op.drop_column('Queries', 'ques')
    ### end Alembic commands ###
