"""empty message

Revision ID: a96c1aed2e8a
Revises: 02f4202766df
Create Date: 2016-10-10 01:05:25.571901

"""

# revision identifiers, used by Alembic.
revision = 'a96c1aed2e8a'
down_revision = '02f4202766df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sign_In', sa.Column('purchase_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sign_In', 'purchase_id')
    ### end Alembic commands ###
