"""empty message

Revision ID: da5a8b566ade
Revises: 50589f022c12
Create Date: 2016-10-14 18:10:33.941313

"""

# revision identifiers, used by Alembic.
revision = 'da5a8b566ade'
down_revision = '50589f022c12'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Sign_In', 'complete_registration',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'Sign_In', ['purchase_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Sign_In', type_='unique')
    op.alter_column('Sign_In', 'complete_registration',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    ### end Alembic commands ###
